### PR TITLE
Update lib versions and usage to simplify code and allow wasm compilation.

### PR DESCRIPTION
**Pull request by dshiell15**
Hi!

Thank you for your implementation of ectoken! I recently began working on a rust ectoken implementation internally for VDMS and then found this repo because there was an existing PR that had been left dormant for too long. 

This PR mainly swaps usage of rust-crypto for aes-gcm and sha2. This helps simplify the code a bit and also now supports compilation to wasm32-wasi target.

I also added a basic test for encode/decode.

Please let me know how it looks to you and if you have any concerns. Thanks!

### CODE REVIEW

**Comment by bburnichon** [comment]
Hello, thanks for your contribution.

We will need to bump minimum requirements before merge of your PR. aes-gcm ^0.8 requires rustc 1.41+. hence fails on CI using version 1.34.0.

**Comment by dshiell15** [comment]
Ok, yes, hopefully that is ok.

If you would like to submit a PR back to the VerizonDigitalMedia repo, I would be happy to approve. However, that repo is not well maintained at the moment, and you already have a CI/CD workflow setup so I wouldn't feel the need. Thank you so much for the prompt attention!

**Comment by bburnichon** [comment]
As indicated on https://github.com/VerizonDigital/ectoken/issues/26 there are no wishes to provide a rust version of the ectoken tool. That was the reason I created this independant repository.

**Comment by dshiell15** [comment]
Ah yes I see. We're going through and splitting the repos out into language specific repos. If you would like to open a PR here: https://github.com/VerizonDigital/rust-ectoken there is interest now to provide a rust version of the tool and I'd be happy to approve. I've added required boilerplate by our open source team - I think only the README.md would conflict.

**Comment by bburnichon** [comment]
I've bumped requirements and also prepared things for a new release. There also is `ectoken` rust package which could be handed back to you I think.

**Comment by dshiell15** [comment]
Great - thank you! My rust account is also dshiell15 if you are ready to transfer ownership. I would like to make sure your contributions as the primary author are maintained if/when you PR to the new VerizonDigital/rust-ectoken repo. Do you have any requests there?

**Comment by bburnichon** [comment]
I just sent you a request to your crates.io account for the ownership of the package. I also opened a pr https://github.com/VerizonDigital/rust-ectoken/pull/2 for the transfer of ownership of source code.

**Comment by dshiell15** [comment]
Accepted all. Thank you again for your contributions!

**Pull request merged**
